# so far only string and integer complexities have been added
# TODO: list methods
# TODO: dictionary methods

complexities = {
    "str.init":"n",
    "str.uninit":"1",
    "str.becomes":"n",
    "str.capitalize":"n",
    "str.title":"n",
    "str.upper":"n",
    "str.swapcase":"n",
    "str.lower":"n",
    "str.zfill":"n",
    "str.casefold":"n",
    "str.in":"n2",
    "str.rstrip":"n",
    "str.lstrip":"n",
    "str.strip":"n",
    "str.index":"n2",
    "str.center":"n",
    "str.find":"n2",
    "str.endswith":"n",
    "str.startswith":"n",
    "str.count":"n2",
    "str.isdigit":"n",
    "str.isalpha":"n",
    "str.islower":"n",
    "str.isupper":"n",
    "str.isalnum":"n",
    "str.replace":"n2",
    "str.encode":"n",
    "str.expandtabs":"n",
    "str.format":"n2",
    "str.format_map":"n2",
    "str.isascii":"n",
    "str.isdecimal ":"n",
    "str.isidentifier":"n",
    "str.isnumberic":"n",
    "str.isprintable":"n",
    "str.isspace":"n",
    "str.istitle":"n",
    "str.join":"n",
    "str.ljust":"n",
    "str.maketrans":"n",
    "str.partition":"n",
    "str.rfind":"n2",
    "str.rindex":"n2",
    "str.rjust":"n",
    "str.rpartition":"n",
    "str.rsplit":"n",
    "str.split":"n",
    "str.splitlines":"n",
    "str.translate":"n",

    "int.init":"n",
    "int.uninit":"n",
    "int.becomes":"n",
    "int.lt":"n",
    "int.gt":"n",
    "int.le":"n",
    "int.ge":"n",
    "int.eq":"n",
    "int.and":"n",
    "int.or":"n",
    "int.not":"n",
    "int.xor":"n",
    "int.test":"n",
    "int.lshift":"n",
    "int.rshift":"n",
    "int.negate":"n",
    "int.add":"n",
    "int.sub":"n",
    "int.mul":"n2",
    "int.div":"n2",
    "int.mod":"n2",
    "int.truediv":"n",
    "int.power":"n4",
    "int.as_integer_ratio":"1",
    "int.bit_count":"n",
    "int.bit_length":"n",
    "int.conjuage":"n",
    "int.from_bytes":"n",
    "int.to_bytes":"n",
    "int.denominator":"1",
    "int.numerator":"1",
    "int.imag":"1",
    "int.real":"1",
    
}



